POST http://localhost:3333/products
Content-Type: application/json

{
    "title": "produto 01",
    "description": "Primeiro produto",
    "price": 30
}

###

GET http://localhost:3333/products?search=produto

###

PUT http://localhost:3333/products/productID
Content-Type: application/json

{
    "title": "Produto 02",
    "description": "Segundo produto",
    "price": 30
}

###

DELETE http://localhost:3333/products/productID

